### ISSUE TITLE
你好，ob 精简版有什么法子可以支持分类+标签么？

### ISSUE THREAD

**Issue by dstweihao** [loveminimal/hugo-theme-virgo#11]
你好，ob 精简版有什么法子可以支持分类+标签么？如果能和完整版一样显示分类和标签那就完美了，谢谢。

**Comment by dstweihao** [comment]
回复那么详细，大佬有心了，多谢了！

**Comment by loveminimal** [comment]
> 回复那么详细，大佬有心了，多谢了！

可以拉取了最新的更新再修改，目前已经把精简版（`ob` 分支）合并到 `master` 分支。

**Comment by dstweihao** [comment]
> > 回复那么详细，大佬有心了，多谢了！
> 
> 可以拉取了最新的更新再修改，目前已经把精简版（`ob` 分支）合并到 `master` 分支。

好的，再次感谢！
