### ISSUE TITLE
[适配请求] 如果能增加Twikoo评论插件就更好了

### ISSUE THREAD

**Issue by happyzhangyyds** [loveminimal/hugo-theme-virgo#15]
【为什么提出这个请求】
  因为twikoo的评论插件对于国内环境支持更好，twikoo支持邮件及时提醒功能，能为博客营造更好的交互环境。

【遇到的问题】
  在自主适配twikoo的时候，发现scss并不能应用到twikoo上，导致排版不够美观。笔者还是技术小白，还在慢慢摸索当中。

【为主题点赞】
  作者大大的这个主题插件非常棒，已在博客中进行了推广[[主题推荐] 宝藏hugo-virgo](https://matrixcore.top/article/hugo-virgo)，非常感谢作者大大的幸苦劳动和无私奉献。

**Comment by happyzhangyyds** [comment]
另外在关闭的issue2当中提到了字体加载速度的问题，我在尝试使用的时候，也体会到字体会影响网站的速度，我之前看到了一款不错的开源字体lxgw，这是开发者的[主页](https://github.com/lxgw)，感觉很棒，其中[ 霞鹜文楷屏幕阅读版](https://github.com/lxgw/LxgwWenKai-Screen)，我觉得视觉效果蛮好的，也许可以试试看呢！

**Comment by loveminimal** [comment]
> 【为什么提出这个请求】 因为twikoo的评论插件对于国内环境支持更好，twikoo支持邮件及时提醒功能，能为博客营造更好的交互环境。
> 
> 【遇到的问题】 在自主适配twikoo的时候，发现scss并不能应用到twikoo上，导致排版不够美观。笔者还是技术小白，还在慢慢摸索当中。
> 
> 【为主题点赞】 作者大大的这个主题插件非常棒，已在博客中进行了推广[[主题推荐] 宝藏hugo-virgo](https://matrixcore.top/article/hugo-virgo)，非常感谢作者大大的幸苦劳动和无私奉献。

这个评论插件听你说，我才知道。
看了下文档，确实不错，及时通知这一点很吸引人。
不过它需要云函数部署，增加了些使用门槛（虽然不多）。

giscus 也是一个不错的评论插件，使用它可以方便地对评论进行统一的管理，如下。只需要前端部署，简单配置后，数据是存储在 Github 上的。

![image](https://github.com/loveminimal/hugo-theme-virgo/assets/23427211/33795b13-ad77-460a-9f9c-7ef30ce0fccf)

**Comment by happyzhangyyds** [comment]
幸苦作者大大了！
