### ISSUE TITLE
文章描述

### ISSUE THREAD

**Issue by 0xo7** [loveminimal/hugo-theme-virgo#16]
请问这个文章描述是怎么写的啊，写在md文件里面的之前嘛

**Comment by loveminimal** [comment]
具体指什么嘞？什么地方的文章描述呢？

**Comment by loveminimal** [comment]
> 请问这个文章描述是怎么写的啊，写在md文件里面的之前嘛

具体指什么嘞？什么地方的文章描述呢？

**Comment by 0xo7** [comment]
> > 请问这个文章描述是怎么写的啊，写在md文件里面的之前嘛
> 
> 具体指什么嘞？什么地方的文章描述呢？

![image](https://github.com/loveminimal/hugo-theme-virgo/assets/67718036/91cb02de-231e-400c-9856-697d0a1f71f8)
就这种文章描述，是在md文件里面加了  嘛，描述默认好像是取80个字

**Comment by loveminimal** [comment]
> > > 请问这个文章描述是怎么写的啊，写在md文件里面的之前嘛
> > 
> > 
> > 具体指什么嘞？什么地方的文章描述呢？
> 
> ![image](https://private-user-images.githubusercontent.com/67718036/329753587-91cb02de-231e-400c-9856-697d0a1f71f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDgzMTksIm5iZiI6MTcxNTQwODAxOSwicGF0aCI6Ii82NzcxODAzNi8zMjk3NTM1ODctOTFjYjAyZGUtMjMxZS00MDBjLTk4NTYtNjk3ZDBhMWY3MWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA2MTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YWVmOWUwYmFiMjRjYjU1NWE0NjMxZDE4YjM3ZjA2NTBjMjJjZDQ2MDNhM2MwYzcxOWIxOWZlNmM2MzRjMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I8Hf_OFW7ZcRyvHo1vpG-rw6sxYaOQjjAw7vA6-moQ8) 就这种文章描述，是在md文件里面加了 嘛，描述默认好像是取80个字

![image](https://github.com/loveminimal/hugo-theme-virgo/assets/23427211/fa1b6ff4-21cb-4dca-8673-dfc80eaa422a)

对的，加上这一行  `<!--more-->` 就可以啦~

**Comment by 0xo7** [comment]
> > > > 请问这个文章描述是怎么写的啊，写在md文件里面的之前嘛
> > > 
> > > 
> > > 具体指什么嘞？什么地方的文章描述呢？
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/67718036/329753587-91cb02de-231e-400c-9856-697d0a1f71f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MDgzMTksIm5iZiI6MTcxNTQwODAxOSwicGF0aCI6Ii82NzcxODAzNi8zMjk3NTM1ODctOTFjYjAyZGUtMjMxZS00MDBjLTk4NTYtNjk3ZDBhMWY3MWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDA2MTMzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5YWVmOWUwYmFiMjRjYjU1NWE0NjMxZDE4YjM3ZjA2NTBjMjJjZDQ2MDNhM2MwYzcxOWIxOWZlNmM2MzRjMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.I8Hf_OFW7ZcRyvHo1vpG-rw6sxYaOQjjAw7vA6-moQ8) 就这种文章描述，是在md文件里面加了 嘛，描述默认好像是取80个字
> 
> ![image](https://private-user-images.githubusercontent.com/23427211/329758776-fa1b6ff4-21cb-4dca-8673-dfc80eaa422a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTU0MzU1MDYsIm5iZiI6MTcxNTQzNTIwNiwicGF0aCI6Ii8yMzQyNzIxMS8zMjk3NTg3NzYtZmExYjZmZjQtMjFjYi00ZGNhLTg2NzMtZGZjODBlYWE0MjJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTExVDEzNDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3YWU2ZTJiZTcyZTU5ZWE1YzgyZWY3MjdmN2IwYjg3ODVlYTZmYWFmYWM1NDQ5NjBmNThkMmM3ZDkzNGYyNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RgAxdKuTpMjJtc5VeRvn7mhQOiYpl7_skhxV3n8yQVA)
> 
> 对的，加上这一行 `<!--more-->` 就可以啦~ 注意 `more` 和 `<!-- -->` 中间不要有空格。

好的，谢谢师傅
