### ISSUE TITLE
求一个exampleSite，文档没说清～～

### ISSUE THREAD

**Issue by supuwoerc** [loveminimal/hugo-theme-virgo#3]
求大佬弄一个一个exampleSite，文档有些简单了，例如搜索归档这些都不太知道咋弄

**Comment by supuwoerc** [comment]
自己猜了猜目录结构，猜出来了哈哈 =。=

**Comment by loveminimal** [comment]
> 自己猜了猜目录结构，猜出来了哈哈 =。=

😂 👍

**Comment by dstweihao** [comment]
> 

一样的，哈哈哈也是猜出来的，试了N久，不得不说我看过不下十几个博客主题，这个是我目前为止是如此满意的一个，真的太感谢了！加油！

**Comment by supuwoerc** [comment]
> 一样的，哈哈哈也是猜出来的，试了N久，不得不说我看过不下十几个博客主题，这个是我目前为止是如此满意的一个，真的太感谢了！加油！

俺也一样
