### ISSUE TITLE
你好，知道为什么css文件总是跳转至github.io么

### ISSUE THREAD

**Issue by dstweihao** [loveminimal/hugo-theme-virgo#4]
你好，知道为什么css维文件总是跳转至github.io么，类似https://ovirgo.com/style.min.20bd185efe9a6c77179f4007cb89793d883bf9ab92c604209b549840b39788ae.css  我在个人域名请求总是跳转至github.io，导致加载失败，腾讯云COS里的文件内容都对过了，确实是个人域名的，谢谢了。

**Comment by loveminimal** [comment]
> 你好，知道为什么css维文件总是跳转至github.io么，类似https://ovirgo.com/style.min.20bd185efe9a6c77179f4007cb89793d883bf9ab92c604209b549840b39788ae.css 我在个人域名请求总是跳转至github.io，导致加载失败，腾讯云COS里的文件内容都对过了，确实是个人域名的，谢谢了。

本地服务是不是每次加载是正常的？

**Comment by dstweihao** [comment]
> 1. 是不是

感谢提供思路！问题已经解决了，是腾讯云 DNS缓存的问题，刷新就可以了额。
