### ISSUE TITLE
你能用 hugo-theme-virgo 发布一个样本网站吗？

### ISSUE THREAD

**Issue by juggernautjp** [loveminimal/hugo-theme-virgo#5]
我想在我的博客上使用Flexsearch的搜索功能。

我试图根据你的博文 [一种简单的雨果本地搜索实现](https://ovirgo.com/posts/hugo-local-search/)，使用 hugo-theme-virgo 主题建立一个样本网站，但无法 我无法实现搜索。

能否请你在 GitHub 上发布一个实现搜索页面的样本网站，与你建立的 [演示网站](https://ovirgo.com/) 上的搜索一样？

**Comment by loveminimal** [comment]
> 我想在我的博客上使用Flexsearch的搜索功能。
> 
> 我试图根据你的博文 [一种简单的雨果本地搜索实现](https://ovirgo.com/posts/hugo-local-search/)，使用 hugo-theme-virgo 主题建立一个样本网站，但无法 我无法实现搜索。
> 
> 能否请你在 GitHub 上发布一个实现搜索页面的样本网站，与你建立的 [演示网站](https://ovirgo.com/) 上的搜索一样？

你好哈，我不知道是否正确理解了你想要表达的意思 ~

- [layouts/partials/_search.html](https://github.com/loveminimal/hugo-theme-virgo/blob/master/layouts/partials/_search.html)
- [static/js/search.js](https://github.com/loveminimal/hugo-theme-virgo/blob/master/static/js/search.js)
- [assets/scss/partials/content/search.scss](https://github.com/loveminimal/hugo-theme-virgo/blob/master/assets/scss/partials/content/search.scss)

搜索页所需的资源如上。

在你现在使用的主题中，按着 [一种简单的 Hugo 本地搜索实现](https://ovirgo.com/posts/hugo-local-search/) 中的描述使用即可。

🎈 如果，你使用的是 hugo-theme-virgo 主题的话，该功能是内置的，不需要做额外操作。

**Comment by loveminimal** [comment]
> 我想在我的博客上使用Flexsearch的搜索功能。
> 
> 我试图根据你的博文 [一种简单的雨果本地搜索实现](https://ovirgo.com/posts/hugo-local-search/)，使用 hugo-theme-virgo 主题建立一个样本网站，但无法 我无法实现搜索。
> 
> 能否请你在 GitHub 上发布一个实现搜索页面的样本网站，与你建立的 [演示网站](https://ovirgo.com/) 上的搜索一样？

[loveminimal/site-template-of-virgo: 使用 hugo-theme-virgo 的主题站点模板](https://github.com/loveminimal/site-template-of-virgo)
