### ISSUE TITLE
Download example site

### ISSUE THREAD

**Issue by ibragimof** [loveminimal/hugo-theme-virgo#7]
I am not familiar with hugo.
Can you give repo with your homepage site content, so I can just download content of all your site and just change texts, pages?
thanks.

**Comment by loveminimal** [comment]
> 



> I am not familiar with hugo. Can you give repo with your homepage site content, so I can just download content of all your site and just change texts, pages? thanks.

[loveminimal/site-template-of-virgo: 使用 hugo-theme-virgo 的主题站点模板](https://github.com/loveminimal/site-template-of-virgo)

**Comment by ibragimof** [comment]
> [loveminimal/site-template-of-virgo: 使用 hugo-theme-virgo 的主题站点模板](https://github.com/loveminimal/site-template-of-virgo)

But there is no layout of such pages like search, archive etc.

**Comment by loveminimal** [comment]
> 



> > [loveminimal/site-template-of-virgo: 使用 hugo-theme-virgo 的主题站点模板](https://github.com/loveminimal/site-template-of-virgo)
> 
> But there is no layout of such pages like search, archive etc.

Actrually, the page like search or archive is just [layouts/_default/single.html](https://github.com/loveminimal/hugo-theme-virgo/blob/master/layouts/_default/single.html). To view it, you will find that. 🤗

**Comment by ibragimof** [comment]
There I see some strange behavior like errors, if I will change page title form "Nav" to "Navigation" (for example), also I couldn't understand the logic of language changing. Would you rewrite docs in english, so others can improve theme with PRs....
however, thanx.

**Comment by loveminimal** [comment]
> There I see some strange behavior like errors, if I will change page title form "Nav" to "Navigation" (for example), also I couldn't understand the logic of language changing. Would you rewrite docs in english, so others can improve theme with PRs.... however, thanx.

Woo, you find that questtion. And you are right.

You cannon change `Nav` to `Navigation`, because `Nav as a  {{ .Title }} ` is necessay to current template logic. The logic of lang changing is simple 😅 , in fact, I just translate some words in the template directly.

Up to now, the features of theme are also approach to stable. If I have enough time, I will create a new readme file in english someday.
