### ISSUE TITLE
评论区是否可以跟随主题更改呢？

### ISSUE THREAD

**Issue by Arrow-Oliver** [loveminimal/hugo-theme-virgo#8]

**Comment by loveminimal** [comment]
这个评论插件使用的是 `<iframe>` ，试了几种方案都无法做到跟随主题颜色更改。

如果，习惯使用暗色主题的话，可以把在 `config.toml` 中 ` [params.utterances]` (129 行左右) 更改成 `github-dark` ，更多主题选项如下：
![image](https://user-images.githubusercontent.com/23427211/229293568-b4db0115-ccae-4dd3-84e2-020910789de3.png)

更多用法可以参考插件的官方文档 [utterances](https://utteranc.es/) 。
